# Generated by Django 4.2.2 on 2023-07-15 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('موبایل', 'موبایل'), ('تبلت ', 'تبلت ')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('Neighbourhood', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('device_status', models.CharField(choices=[('در حد نو', 'در حد نو'), (' کار کرده', 'کار کرده '), (' نیاز به تعمیر ', 'نیاز به تعمیر  ')], max_length=50)),
                ('brand_originality', models.CharField(choices=[('اصل', 'اصل'), ('غیر اصل ', 'غیر اصل ')], max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Product/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'db_table': 'Product Photos',
            },
        ),
    ]
