# Generated by Django 4.2.2 on 2023-07-23 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_originality',
            field=models.CharField(choices=[('اصل', 'اصل'), ('غیر اصل', 'غیر اصل')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('موبایل', 'موبایل'), ('تبلت', 'تبلت')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_status',
            field=models.CharField(choices=[('در حد نو', 'در حد نو'), ('کار کرده', 'کار کرده'), ('نیاز به تعمیر', 'نیاز به تعمیر')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Product Comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
