# Generated by Django 4.2.2 on 2023-07-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productlike'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productlike',
            table='Product Like',
        ),
    ]
